import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { auth } from "~/lib/auth/server";
import { TRPCReactProvider } from "~/trpc/react";
import { UserMenu } from "./_components/user-menu";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	let userName: string | null = null;

	try {
		const result = await auth.getSession();
		const user = result.data?.user;
		if (user?.name) {
			userName = user.name;
		} else if (user?.email) {
			userName = user.email.split("@")[0] ?? null;
		}
	} catch {
		userName = null;
	}

	return (
		<html className={`${geist.variable}`} lang="en">
			<body>
				<TRPCReactProvider>
					{userName && (
						<header className="fixed top-0 right-0 z-50 p-4">
							<UserMenu userName={userName} />
						</header>
					)}
					{children}
				</TRPCReactProvider>
			</body>
		</html>
	);
}
